version : '3'

services:
    php:
        build: .
        image: registry.gitlab.com/w3blogfr/demo-gitlab-docker
        volumes: 
             - ./html:/var/www/html
        environment:
             - BUILD_VERSION="1.4"
        ports:
             - 8080:80