version: '3'
services:
 ubuntu:
  image: "arunvelsriram/utils"
  command: "tail -f /dev/null"
  ports:
   - "80:80"
   - "8080:8080"
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
 whoami:
  image: containous/whoami
  deploy:
   replicas: 3