apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  labels:
    app: whoami-service
  namespace: whoami
spec:
  type: NodePort  
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: whoami
